name: Java Syntax Check

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Chạy khi có PR mở hoặc cập nhật

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    
    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK (Checkstyle yêu cầu JDK để kiểm tra mã Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Hoặc phiên bản Java bạn đang sử dụng
          distribution: 'adoptopenjdk'

      # Bước 3: Cài đặt Checkstyle
      - name: Install Checkstyle
        run: |
          curl -s https://checkstyle.org/gettingstarted.html | bash  # Tải và cài đặt Checkstyle

      # Bước 4: Chạy Checkstyle để kiểm tra mã Java
      - name: Run Checkstyle
        run: |
          checkstyle -c /google_checks.xml src/main/java/com/project/shopapp  # Đường dẫn đến mã nguồn Java của bạn
          
      # Bước 5: Thông báo lỗi nếu phát hiện vấn đề cú pháp
      - name: Notify Jira if syntax error
        if: failure()  # Chỉ thực thi nếu Checkstyle phát hiện lỗi
        run: |
          curl -u ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
               "project": { "key": "CON" },  # Project Key trong Jira
               "summary": "❌ Syntax error in PR #${{ github.event.number }}",
               "description": "Syntax error found in PR: ${{ github.event.pull_request.html_url }}",
               "issuetype": { "name": "Bug" }
            }
          }' \
          https://thoai12309.atlassian.net/rest/api/2/issue/
