name: PR Merge Check

on:
  pull_request:
    types: [closed]  # Chỉ khi PR được đóng lại (hoặc merge)

jobs:
  check-merge:
    runs-on: ubuntu-latest
    
    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK và Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Hoặc phiên bản Java bạn đang sử dụng
          distribution: 'adoptopenjdk'

      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.8.1'  # Hoặc phiên bản Maven bạn đang sử dụng

      # Bước 3: Cài đặt dependencies và build ứng dụng
      - name: Build with Maven
        run: mvn clean install -DskipTests  # Chạy lệnh clean và install, bỏ qua tests

      # Bước 4: Chạy các bài kiểm tra (tests)
      - name: Run tests
        run: mvn test  # Chạy tất cả các bài test trong dự án Spring Boot của bạn

      # Bước 5: Thông báo lỗi nếu test thất bại
      - name: Notify Jira if failed
        if: failure()  # Chỉ thực thi nếu bước trên gặp lỗi
        run: |
          curl -u ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
               "project": { "key": "CON" },  # Project Key trong Jira
               "summary": "❌ Merge failed in PR #${{ github.event.number }}",
               "description": "Build or test failed after merging PR: ${{ github.event.pull_request.html_url }}",
               "issuetype": { "name": "Bug" }
            }
          }' \
          https://thoai12309.atlassian.net/rest/api/2/issue/
