name: PR Merge Check

on:
  pull_request:
    types: [closed]  # Chỉ khi PR được đóng lại (hoặc merge)

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm ci
          npm run test

      - name: Notify Jira if failed
        if: failure()  # Nếu kiểm tra bị lỗi
        run: |
          curl -u ${{ secrets.thoai12309@gmail.com }}:${{ secrets.ATATT3xFfGF0nc-yMA3DUKe3SdAFAy1-TvYGRJaZ55xVjfeDiEXzcSXjaOfZNwd8SUPP4HycSZ9_6C5SM7Jz8U1ndQrJwLjmGjOVD-Pgy9uXwV8e1sQaPZ6MpVEP1JXntGSWX7mdAVTRTr01jZeZHV3NbHLuvl1sxlO43S6MaZivmmKHKEoXZn4=BE5F609F }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
              "project": { "key": "ABC" },
              "summary": "❌ Merge failed in PR #${{ github.event.number }}",
              "description": "Build or test failed after merging PR: ${{ github.event.pull_request.html_url }}",
              "issuetype": { "name": "Bug" }
            }
          }' \
          https://yourcompany.atlassian.net/rest/api/2/issue/
